---
dist: xenial
language: generic
stages:
  - lint
  - build and deploy
jobs:
  include:
    - stage: lint
      name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -u "$UID" -v "$PWD:$PWD" -w "$PWD" lpenz/omnilint
      if: NOT branch ~= .*-.*
    - stage: build and deploy
      name: docker image
      if: branch ~= .*-.*
      addons: { apt: { packages: [ debootstrap, qemu-user-static, golang, scons ] } }
      install:
        - sudo cp -Rd debootstrap_scripts/* /usr/share/debootstrap/scripts/
      script:
        - go get golang.org/x/net/html
        - while sleep 9m; do echo "=====[ ping ]====="; done &
        - PING_PID="$!"
        - scons dockerhub-set-descriptions
        - ./travis-script.sh _image.txt
        - kill "$PING_PID"
        - cat _image.txt
        - . _image.txt
        - export IMAGE DESCRIPTION
      before_deploy:
        - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
      deploy:
        - provider: script
          skip_cleanup: true
          script: ./travis-deploy.sh
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ .*-.*
    - name: status page
      if: NOT branch ~= .*-.*
      addons: { apt: { packages: [ scons, golang ] } }
      script:
        - go get golang.org/x/net/html
        - while sleep 9m; do echo "=====[ ping ]====="; done &
        - PING_PID="$!"
        - scons
        - kill "$PING_PID"
        - rm -f .gitignore
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        target-branch: gh-pages
        on:
          branch: master
