---
# Copyright (C) 2021 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.
name: CI
on:
  pull_request:
    branches:
      - main
      - devel
  push:
    branches:
      - main
      - devel
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker://lpenz/omnilint:0.5
  status-page-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/status-page
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
