---
# Copyright (C) 2021 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.
name: docker-build-distro
on:
  push:
    branches-ignore:
      - main
      - devel
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: >
          sudo apt-get update;
          sudo apt-get install -y --no-install-recommends debootstrap
      - run: >
          docker build -t docker-debian-releases .;
          docker run --rm -u 0 -v "${PWD}:$PWD" -w "$PWD" -e PERSONAL_TOKEN docker-debian-releases
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - uses: docker/setup-qemu-action@v2.1.0
      - run: sudo cp -Rd debootstrap_scripts/* /usr/share/debootstrap/scripts/
      - id: branch
        run: ./branch-info
      - id: build
        run: >
          ./docker-create-debian-image
          -m "${{ steps.branch.outputs.mirror }}"
          -i "${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.branch.outputs.image }}"
          "${{ steps.branch.outputs.dist }}"
          "${{ steps.branch.outputs.arch }}"
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.branch.outputs.image }}"
      - run: >
          ./dockerhub-set-descriptions
          "${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.branch.outputs.image }}"
          "${{ steps.build.outputs.description }}"
          "Automatically updated via https://github.com/lpenz/docker-debian-releases/"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  update-status-page:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: benc-uk/workflow-dispatch@v1.2.1
        with:
          workflow: status-page-deploy
          token: ${{ secrets.PERSONAL_TOKEN }}
