---
# Copyright (C) 2021 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.
name: status-page-deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
concurrency:
  group: status-page-deploy
  cancel-in-progress: true
jobs:
  status-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/status-page
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - run: rm -f .gitignore
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
          single-commit: true
          clean: true
